### ISSUE TITLE
Visual Cues improvements

### ISSUE THREAD

**Issue by damianhxy** [autolab/Autolab#2031]
- Does not correctly collapse to 2 columns on small screens
- Clearfix does not change depending on number of columns
- (Requested by 122) Display start and end date (and maybe more) as a mouse-over instead
- (Requested by Joey) show on course index page too

Quick and dirty prototype:
![Screenshot 2024-01-16 at 00 38 29](https://github.com/autolab/Autolab/assets/9074856/2725cfb6-9b87-4d1b-8c50-35dc422714e9)
```css
.collection-item .date {
  display: none;
}

.collection-item:hover .date {
  display: block;
}
```

Possibly add a small icon to draw user attention
![Picture1](https://github.com/autolab/Autolab/assets/9074856/8eadd1d0-9bd9-4718-80d5-4f0b23d097ec)
