### ISSUE TITLE
Autolab production setup error: undefined symbol `sqlite3_column_database_name`

### ISSUE THREAD

**Issue by magsol** [autolab/Autolab#678]
Hi all,

I'm in the process of setting up Autolab for a course I'm teaching this semester. I have an Ubuntu 16.04 VM up and running (desktop version, so I had to install some extra packages). I *think* I followed the instructions correctly, but every time I access the main page through the browser, I get the following error message (changed deployment to "development" so I could more easily diagnose the error, but this is what I was getting even when deployment was "production"):

<img width="1270" alt="screen shot 2016-08-13 at 12 03 08 pm" src="https://cloud.githubusercontent.com/assets/135417/17651700/8891a9d0-623a-11e6-9b4f-3a3525dbd92d.png">

I've gone through the Autolab install, Tango, and Docker required for production deployment, as well as installing and configuring Apache 2 as the webserver. Running the test deployment via `bundle exec rails s -p 3000` worked just fine. I'm using Python 2.7.12 from Anaconda.

Happy to provide any additional information.

**Comment by ymzong** [comment]
Hey @magsol, this seems like an issue with loading `sqlite` library (version mismatch?), and I'm not exactly sure the reason why it happens (we use `mysql` in our production systems).

Would you be willing and able to switch the underlying database to mysql? (the database config is in `config/database.yml`) If not, we will try to take a further look at your issue.

Thanks!

**Comment by magsol** [comment]
I guess that's the weird part--here's my `config/database.yml` file:

```
development:
  adapter: mysql2
  database: username_autolab_development
  pool: 5
  username: username
  password: 'password'
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

production:
  adapter: mysql2
  database: username_autolab_production
  pool: 5
  username: username
  password: 'password'
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
```

The `test` flavor is the same thing. As far as I know, I'm using MySQL everywhere--not sure why `sqlite` is being invoked?
